# See the dedicated "version" documentation section.
version: "2"
linters:
  # See the dedicated "linters" documentation section.
  default: all
  disable:
    - depguard
    - wrapcheck
    - nonamedreturns
  settings:
    varnamelen:
      ignore-names:
        - tx
        - db
      ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: line-length-limit
          arguments: [120]

      
