name: Push to main branch workflow

on:
  push:
    branches:
      - main

env:
  go-version: '1.24'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd-path: [ './cmd/service/main.go' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Install dependencies
        run: go mod download -x
      - name: Build binary
        run: go build -v ${{ matrix.cmd-path }}

  dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:$BUILD_DATE-${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:$BUILD_DATE-${{ github.sha }}
