name: Pull request workflow

on:
  pull_request:

env:
  go-version: '1.24'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd-path: [ './cmd/service/main.go' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Install dependencies
        run: go mod download -x
      - name: Build binary
        run: go build -v ${{ matrix.cmd-path }}
